services:
    watchtower:
      image: containrrr/watchtower:latest
      container_name: watchtower
      restart: unless-stopped
      networks:
          - laravel
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      environment:
          - WATCHTOWER_SCOPE=php-only
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_POLL_INTERVAL=300

    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        command: >
            tunnel --no-autoupdate run
            --token ${CLOUDFLARE_TUNNEL_TOKEN}
        networks:
            - laravel
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
          - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel-php
        networks:
            - laravel
        depends_on:
            - pg
        labels:
            - "com.centurylinklabs.watchtower.scope=php-only"

    pg:
        image: postgres:16.6-alpine3.20
        container_name: postgres_laravel
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=4892ae0405ce4bff9d84cb65200788d4
            - POSTGRES_DB=app-laravel
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel
    pgbouncer:
        image: edoburu/pgbouncer:v1.25.1-p0
        container_name: pgbouncer
        depends_on:
            - pg
        ports:
            - "5432:5432"
        environment:
            - DB_USER=docker
            - DB_PASSWORD=4892ae0405ce4bff9d84cb65200788d4
            - DB_HOST=pg
            - DB_NAME=app-laravel
            - POOL_MODE=transaction
            - MAX_CLIENT_CONN=100
            - DEFAULT_POOL_SIZE=20
            - AUTH_TYPE=scram-sha-256
        networks:
            - laravel
volumes:
    postgres_data:
networks:
    laravel:

